language: node_js
node_js:
  - '10'
install: npm install
stages:
  - name: deploy
jobs:
  includes:
    - stage: deploy
      script:
        - echo "npm neploying start...."
        - npm run build
        - echo "npm deploying finished..."
      deploy:
        provider: npm
        email: 411568765@qq.com
        api_key: '$NPM_TOKEN'
        skip_cleanup: true
        on:
          tags: true
          branch: master
        tag: latest
        condition: '$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$'
